# Generated by Django 4.0.6 on 2022-08-15 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geektech', '0002_panier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_produit', models.CharField(max_length=200)),
                ('pTotal', models.IntegerField(default=0)),
                ('quantite', models.IntegerField(default=0)),
                ('livraison', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
            ],
        ),
    ]
